blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussion
    url: https://community.home-assistant.io/t/actions-card-add-tap-hold-double-tap-actions-to-any-card/888990
    about: Ask questions and discuss the card with other users in the Home Assistant Community Forum
  - name: 📖 Documentation
    url: https://github.com/nutteloost/actions-card#readme
    about: Read the full documentation and examples